'use client';

import { useCallback, useEffect, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDown, ArrowRight, Check, Flower2, Gift, Leaf, Minus, Plus, Search, ShoppingBag, Truck, X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { products, sanitizeCart, getTotals, updateQuantity, won, type Product, type Cart } from '@/lib/shop';
import { Button } from '@/components/ui/button';

export default function Home() {
  const [category,setCategory]=useState('all');
  const [searchOpen,setSearchOpen]=useState(false);
  const [query,setQuery]=useState('');
  const [cart,setCart]=useState<Cart>({});
  const [ready,setReady]=useState(false);
  const [cartOpen,setCartOpen]=useState(false);
  const [selected,setSelected]=useState<Product|null>(null);
  const [quantity,setQuantity]=useState(1);
  const [toast,setToast]=useState('');
  const [checkout,setCheckout]=useState(false);
  const [complete,setComplete]=useState(false);
  const totals=getTotals(cart);
  const filtered=products.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.note} ${p.english}`.toLowerCase().includes(query.trim().toLowerCase()));
  useEffect(()=>{try{setCart(sanitizeCart(JSON.parse(localStorage.getItem('onggul-cart')||'{}')));}catch{}setReady(true);},[]);
  useEffect(()=>{if(ready)try{localStorage.setItem('onggul-cart',JSON.stringify(cart));}catch{}},[cart,ready]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(timer);},[toast]);
  const add=useCallback((product:Product,qty=1)=>{setCart(previous=>updateQuantity(previous,product.id,Math.min(20,(previous[product.id]||0)+qty)));setToast(`${product.name}을 장바구니에 담았어요.`);},[]);
  function openProduct(p:Product){setSelected(p);setQuantity(1);}
  function filterTo(value:string){setCategory(value);setQuery('');document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});}
  useEffect(()=>{
    type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
    const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const controller=new AbortController();
    const tool:Tool={name:'add_honey_to_cart',title:'꿀 장바구니에 담기',description:'시연용 장바구니에 꿀을 추가하고 장바구니를 엽니다. 실제 주문이나 결제는 하지 않습니다.',inputSchema:{type:'object',properties:{productId:{type:'string',enum:products.map(p=>p.id)},quantity:{type:'integer',minimum:1,maximum:20}},required:['productId','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const value=input as {productId?:unknown;quantity?:unknown};if(!value||typeof value!=='object'||Object.keys(value).some(k=>!['productId','quantity'].includes(k)))throw new Error('Invalid input');const p=products.find(p=>p.id===value.productId);if(!p||typeof value.quantity!=='number'||!Number.isInteger(value.quantity)||value.quantity<1||value.quantity>20)throw new Error('Invalid product or quantity');flushSync(()=>{add(p,value.quantity as number);setCartOpen(true);});return{status:'added_to_demo_cart',productId:p.id,requestedQuantity:value.quantity,maximumPerProduct:20,orderPlaced:false};}};
    try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();
  },[add]);
  return <>
    <div className="announcement">마음을 전하는 가장 달콤한 방법 <span>5만원 이상 무료배송 <ArrowRight size={12}/></span></div>
    <header className="header"><a className="brand" href="#" aria-label="온꿀 홈">온꿀<span>ONGGUL</span></a><nav aria-label="주 메뉴"><a href="#shop">모든 꿀</a><a href="#gift">선물하기 <span className="nav-dot"/></a><a href="#story">온꿀 이야기</a><a href="#guide">꿀 취향 찾기</a></nav><div className="header-tools"><Button variant="ghost" size="icon" aria-label="상품 검색" onClick={()=>setSearchOpen(true)}><Search/></Button><Button variant="ghost" size="icon" aria-label={`장바구니 ${totals.count}개`} onClick={()=>setCartOpen(true)}><ShoppingBag/></Button><span className="cart-count">{totals.count}</span></div></header>
    <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> FROM NATURE, WITH LOVE</p><h1>자연이 차곡차곡,<br/>당신의 하루에 <em>꿀.</em></h1><p className="hero-description">꽃이 피고, 벌이 날고, 시간이 쌓여 완성된 달콤함.<br/>자연의 온기를 담은 꿀 한 스푼을 만나보세요.</p><a className="primary-link" href="#shop">나에게 맞는 꿀 만나기 <ArrowRight size={17}/></a><div className="hero-note"><Flower2 size={17}/><span>꽃마다 다른 향, 취향마다 다른 달콤함</span></div></div><div className="hero-image"><img src="/images/hero.png" alt="따뜻한 햇살 아래 온꿀 꿀병과 벌집, 나무 허니 디퍼" fetchPriority="high"/><div className="round-seal">A LITTLE HONEY<span>매일을<br/>달콤하게</span> A LITTLE HAPPINESS</div><div className="image-caption">SLOWLY MADE. SIMPLY GOOD.</div></div><div className="hero-bottom"><span>좋은 하루는 작은 한 스푼에서 시작되니까.</span><a href="#shop" aria-label="상품으로 내려가기"><ArrowDown size={17}/></a></div></section>
    <div className="benefits"><div><Flower2/><span>꽃에서 시작된 달콤함</span></div><div><Leaf/><span>취향에 맞춰 고르는 꿀</span></div><div><Gift/><span>마음을 담은 선물</span></div><div><Truck/><span>5만원 이상 무료배송</span></div></div>
    <section id="shop" className="section shop-section"><div className="section-heading"><div><p className="eyebrow">OUR HONEY COLLECTION</p><h2>어떤 달콤함을 좋아하세요?</h2><p>가볍고 은은하게, 혹은 깊고 진하게. 나만의 꿀을 찾아보세요.</p></div><a className="text-link" href="#guide">내 꿀 취향 찾기 <ArrowRight size={16}/></a></div><div className="filter-row">{[{id:'all',name:'모든 꿀'},{id:'daily',name:'데일리 꿀'},{id:'rich',name:'깊은 풍미'},{id:'gift',name:'선물 세트'}].map(filter=><Button key={filter.id} onClick={()=>setCategory(filter.id)} aria-pressed={category===filter.id} className={`filter ${category===filter.id?'active':''}`} variant="ghost">{filter.name}{filter.id==='all'&&<span>4</span>}</Button>)}<span className="collection-note">A spoonful of something good.</span></div>
    {query&&<div className="search-status">“{query}” 검색 결과 {filtered.length}개 <Button variant="ghost" size="icon" aria-label="검색 초기화" onClick={()=>setQuery('')}><X size={14}/></Button></div>}
    <div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className={`product-image product-${p.index}`}><button className="product-photo-button" onClick={()=>openProduct(p)} aria-label={`${p.name} 상세 보기`}><span className="catalog-photo" role="img" aria-label={p.name} style={{backgroundPosition:`${p.index*100/3}% center`}}/></button><span className="product-badge">{p.badge}</span><Button className="quick-add" variant="outline" size="icon" aria-label={`${p.name} 장바구니 담기`} onClick={()=>add(p)}><ShoppingBag size={17}/></Button></div><p className="product-note">{p.note}</p><h3><button onClick={()=>openProduct(p)}>{p.name}</button><span>{p.weight}</span></h3><p className="product-price">{won(p.price)}<span>원</span></p></article>)}</div>
    {filtered.length===0&&<div className="empty-state"><Search size={28}/><h3>아직 맞는 꿀을 찾지 못했어요.</h3><p>‘아카시아’, ‘밤’, ‘선물’로 다시 검색해보세요.</p><Button variant="outline" onClick={()=>{setQuery('');setCategory('all');}}>모든 꿀 보기</Button></div>}
    <p className="demo-note">온꿀은 브랜드 시안입니다. 상품 이미지와 가격은 예시이며 실제 주문·결제는 진행되지 않습니다.</p></section>
    <section id="gift" className="gift-banner"><div><p className="eyebrow">SWEET LITTLE GIFT</p><h2>고마운 마음에,<br/>달콤함을 더해요.</h2><p>말로 다 전하지 못한 마음, 온꿀 한 상자에 담아.</p><button className="text-link" onClick={()=>filterTo('gift')}>선물 세트 둘러보기 <ArrowRight size={17}/></button></div><div className="gift-photo"><img src="/images/hero.png" alt="소중한 분에게 전하는 온꿀 선물" loading="lazy"/></div></section>
    <section id="story" className="story-section section"><span className="eyebrow">OUR LITTLE PHILOSOPHY</span><h2>꿀 한 병에 담고 싶은 건,<br/>자연의 온기입니다.</h2><p>바쁜 하루에도 잠깐의 여유는 필요하니까.<br/>갓 구운 빵 위에, 따뜻한 차 한 잔에, 소중한 사람의 식탁에.<br/>온꿀은 일상의 작은 순간이 조금 더 달콤해지기를 바랍니다.</p><Flower2 size={30}/></section>
    <section id="guide" className="guide section"><div className="section-heading"><div><p className="eyebrow">FIND YOUR SWEET MOMENT</p><h2>당신의 일상에 어울리는 한 스푼.</h2></div></div><div className="guide-grid"><article><span>01 / LIGHT & SOFT</span><h3>아침을 가볍게 시작할 때</h3><p>요거트와 따뜻한 차에는<br/>맑고 부드러운 아카시아 꿀.</p><button className="guide-link" onClick={()=>openProduct(products.find(p=>p.id==='acacia')!)}>아카시아 꿀 보기 <ArrowRight size={16}/></button></article><article><span>02 / FLORAL & BALANCED</span><h3>평범한 간식도 특별하게</h3><p>바삭한 토스트와 과일에는<br/>꽃향 가득한 야생화 꿀.</p><button className="guide-link" onClick={()=>openProduct(products.find(p=>p.id==='wildflower')!)}>야생화 꿀 보기 <ArrowRight size={16}/></button></article><article><span>03 / DEEP & RICH</span><h3>하루 끝, 깊은 풍미를 즐길 때</h3><p>진한 치즈와 견과류에는<br/>쌉싸름한 여운의 밤꿀.</p><button className="guide-link" onClick={()=>openProduct(products.find(p=>p.id==='chestnut')!)}>밤꿀 보기 <ArrowRight size={16}/></button></article></div></section>
    <section className="faq section"><div><p className="eyebrow">A FEW SWEET ANSWERS</p><h2>궁금한 이야기를 모았어요.</h2></div><div className="faq-list"><details><summary>어떤 꿀을 골라야 할지 모르겠어요.</summary><p>부드러운 맛을 원하면 아카시아 꿀, 풍성한 꽃향을 좋아하면 야생화 꿀, 쌉싸름하고 묵직한 풍미를 원하면 밤꿀을 선택해보세요. 상품을 누르면 맛의 진하기와 추천 조합을 비교할 수 있어요.</p></details><details><summary>선물 세트는 어떻게 구성되나요?</summary><p>시연용 선물 세트는 아카시아 꿀 250g과 야생화 꿀 250g, 선물 상자로 구성되어 있습니다. 실제 판매 시 구성과 포장 정보를 확정할 예정입니다.</p></details><details><summary>배송비는 얼마인가요?</summary><p>시연용 배송 정책은 기본 3,000원이며, 상품 금액 50,000원 이상이면 무료입니다. 실제 배송 지역, 일정, 추가 배송비는 판매 시작 전 확정됩니다.</p></details><details><summary>지금 실제로 주문할 수 있나요?</summary><p>현재는 쇼핑몰 시연 버전입니다. 상품 선택, 장바구니, 주문 내용 확인을 체험할 수 있으며 실제 결제나 배송은 발생하지 않습니다.</p></details></div></section>
    </main>
    <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog"><DialogTitle>어떤 달콤함을 찾으세요?</DialogTitle><DialogDescription>상품명이나 맛으로 검색해보세요.</DialogDescription><form onSubmit={e=>{e.preventDefault();setSearchOpen(false);setCategory('all');document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});}}><label className="sr-only" htmlFor="product-search">상품 검색</label><Input id="product-search" autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="아카시아, 밤꿀, 선물…"/><Button type="submit" aria-label="검색 실행"><Search size={18}/></Button></form><div className="search-suggestions">{['아카시아','밤','선물'].map(term=><Button key={term} variant="outline" onClick={()=>{setQuery(term);setCategory('all');setSearchOpen(false);document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});}}>{term}</Button>)}</div></DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="product-dialog">{selected&&<><div className="detail-photo"><span className="catalog-photo" role="img" aria-label={selected.name} style={{backgroundPosition:`${selected.index*100/3}% center`}}/></div><div className="detail-copy"><p className="eyebrow">{selected.english}</p><DialogTitle className="detail-title">{selected.name}</DialogTitle><DialogDescription className="detail-description">{selected.description}</DialogDescription><div className="flavor-profile"><div><span>꽃향</span><span aria-label={`5단계 중 ${selected.floral}`}>{[1,2,3,4,5].map(n=><i key={n} className={n<=selected.floral?'filled':''}/>)}</span></div><div><span>풍미의 진하기</span><span aria-label={`5단계 중 ${selected.intensity}`}>{[1,2,3,4,5].map(n=><i key={n} className={n<=selected.intensity?'filled':''}/>)}</span></div></div><p className="pairing"><span>함께하면 좋아요</span>{selected.pairing}</p><div className="detail-price"><span>{selected.weight}</span><strong>{won(selected.price)}원</strong></div><div className="purchase-row"><div className="quantity-control"><Button variant="ghost" size="icon" aria-label="수량 줄이기" disabled={quantity<=1} onClick={()=>setQuantity(q=>q-1)}><Minus/></Button><span aria-live="polite">{quantity}</span><Button variant="ghost" size="icon" aria-label="수량 늘리기" disabled={quantity>=20} onClick={()=>setQuantity(q=>q+1)}><Plus/></Button></div><Button onClick={()=>{add(selected,quantity);setSelected(null);setCartOpen(true);}}>{won(selected.price*quantity)}원 · 담기 <ShoppingBag/></Button></div><p className="detail-disclaimer">예시 상품 · 실제 주문 및 결제 불가</p></div></>}</DialogContent></Dialog>
    <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet"><div className="cart-heading"><p className="eyebrow">YOUR SWEET SELECTION</p><SheetTitle>장바구니 <span>{totals.count}</span></SheetTitle><SheetDescription>당신의 하루를 달콤하게 채워보세요.</SheetDescription></div>{totals.count===0?<div className="empty-state cart-empty"><ShoppingBag size={38}/><h3>아직 담긴 달콤함이 없어요.</h3><p>취향에 맞는 꿀 한 병을 골라보세요.</p><Button onClick={()=>{setCartOpen(false);filterTo('all');}}>꿀 만나러 가기 <ArrowRight/></Button></div>:<><div className="shipping-notice"><Truck size={17}/>{totals.shipping===0?'무료배송 금액을 채웠어요!':`${won(50000-totals.subtotal)}원 더 담으면 무료배송`}</div><div className="cart-items">{products.filter(p=>cart[p.id]).map(p=><div className="cart-item" key={p.id}><div className="cart-thumb"><span className="catalog-photo" role="img" aria-label={p.name} style={{backgroundPosition:`${p.index*100/3}% center`}}/></div><div className="cart-item-info"><h3>{p.name}</h3><p>{p.weight}</p><div className="quantity-control"><Button variant="ghost" size="icon" aria-label={`${p.name} 수량 줄이기`} disabled={cart[p.id]<=1} onClick={()=>setCart(c=>updateQuantity(c,p.id,c[p.id]-1))}><Minus/></Button><span>{cart[p.id]}</span><Button variant="ghost" size="icon" aria-label={`${p.name} 수량 늘리기`} disabled={cart[p.id]>=20} onClick={()=>setCart(c=>updateQuantity(c,p.id,c[p.id]+1))}><Plus/></Button></div></div><div className="cart-item-end"><Button variant="ghost" size="icon" aria-label={`${p.name} 삭제`} onClick={()=>setCart(c=>updateQuantity(c,p.id,0))}><X/></Button><strong>{won(p.price*cart[p.id])}원</strong></div></div>)}</div><div className="cart-summary"><div><span>상품 금액</span><span>{won(totals.subtotal)}원</span></div><div><span>배송비</span><span>{totals.shipping===0?'무료':`${won(totals.shipping)}원`}</span></div><div className="cart-total"><span>총 결제 예정 금액</span><strong>{won(totals.total)}원</strong></div><Button className="checkout-button" onClick={()=>{setCartOpen(false);setCheckout(true);setComplete(false);}}>주문 내용 확인 <ArrowRight/></Button><p>시연용 쇼핑몰로, 실제 결제는 진행되지 않습니다.</p></div></>}</SheetContent></Sheet>
    <Dialog open={checkout} onOpenChange={setCheckout}><DialogContent className="checkout-dialog">{complete?<><div className="complete-icon"><Check size={28}/></div><DialogTitle>달콤한 선택을 마쳤어요.</DialogTitle><DialogDescription>주문 흐름 체험이 완료되었습니다. 실제 주문·결제·배송은 발생하지 않았으며 장바구니는 그대로 보관됩니다.</DialogDescription><Button onClick={()=>setCheckout(false)}>계속 둘러보기 <ArrowRight/></Button></>:<><p className="eyebrow">ORDER PREVIEW</p><DialogTitle>주문 내용을 확인해주세요.</DialogTitle><DialogDescription>실제 결제가 없는 주문 흐름 체험입니다.</DialogDescription><div className="order-items">{products.filter(p=>cart[p.id]).map(p=><div key={p.id}><span>{p.name} × {cart[p.id]}</span><strong>{won(p.price*cart[p.id])}원</strong></div>)}</div><div className="order-shipping"><span>배송비</span><span>{totals.shipping===0?'무료':`${won(totals.shipping)}원`}</span></div><div className="cart-total"><span>총 결제 예정 금액</span><strong>{won(totals.total)}원</strong></div><p className="checkout-note">상품과 가격은 예시입니다. 현재 결제 서비스가 연결되어 있지 않아 배송지나 결제 정보를 수집하지 않습니다.</p><Button className="checkout-button" disabled={!totals.count} onClick={()=>setComplete(true)}>주문 흐름 체험 완료 <Check/></Button></>}</DialogContent></Dialog>
    {toast&&<div className="toast" role="status"><Check size={17}/>{toast}<Button variant="ghost" onClick={()=>{setToast('');setCartOpen(true);}}>보기 <ArrowRight size={14}/></Button></div>}
    <footer><div className="footer-top"><a className="brand" href="#">온꿀<span>ONGGUL</span></a><p>자연의 온기를, 당신의 하루에.</p><a href="#shop">달콤한 일상 시작하기 <ArrowRight size={16}/></a></div><div className="footer-bottom"><span>© 2026 ONGGUL. A little honey, a little happiness.</span><span>브랜드·상품·배송 정책은 시연용입니다.</span></div></footer>
  </>;
}
